apiVersion: batch/v1
kind: Job
metadata:
  name: fraud-loader-job
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: loader
        image: fraud-detection-loader:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: fraud-app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: fraud-app-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fraud-redis-secret
              key: redis-password
